"""add_meal_name_to_meal_table

Revision ID: b994e4c45504
Revises: 9dd3f246db1e
Create Date: 2024-12-15 08:35:07.204232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b994e4c45504'
down_revision: Union[str, None] = '9dd3f246db1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('meal_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'meal_name')
    # ### end Alembic commands ###
